services:
  # Contenedor de la Base de Datos
  db:
    image: mysql:8.0
    container_name: libreria_db
    restart: always
    environment:
      MYSQL_DATABASE: libreria_ies
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./database_init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  # Contenedor del Backend (Laravel)
  backend:
    build:
      context: ./backend
    container_name: libreria_backend
    restart: always
    ports:
      - "8002:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  # Contenedor del Frontend (Angular)
  frontend:
    build:
      context: ./frontend
    container_name: libreria_frontend
    ports:
      - "4201:4201"
    volumes:
      - ./frontend:/app
      - /app/node_modules 

volumes:
  db_data: